export const CHARACTER_API_REQUEST = 'CHARACTER_API_REQUEST'
export const CHARACTER_API_SUCCESS = 'CHARACTER_API_SUCCESS'
export const CHARACTER_API_FAIL = 'CHARACTER_API_FAIL'

export const CHARACTER_API_SEARCH_REQUEST = 'CHARACTER_API_SEARCH_REQUEST'
export const CHARACTER_API_SEARCH_SUCCESS = 'CHARACTER_API_SEARCH_SUCCESS'
export const CHARACTER_API_SEARCH_FAIL = 'CHARACTER_API_SEARCH_FAIL'
